### ISSUE TITLE
tuple index out of range on /admin/blog/entry/add/

### ISSUE THREAD

**Issue by simonw** [simonw/simonwillisonblog#323]
Got this error trying to post a new entry:

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/9599/224331909-b4584d57-3123-4ea5-8eb7-4c561ebdb234.png">

**Comment by simonw** [comment]
```
Environment:


Request Method: POST
Request URL: http://0.0.0.0:8033/admin/blog/entry/add/

Django Version: 5.0
Python Version: 3.10.10
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_sql_dashboard',
 'blog',
 'redirects',
 'feedstats',
 'debug_toolbar')
Installed Middleware:
('debug_toolbar.middleware.DebugToolbarMiddleware',
 'redirects.middleware.redirect_middleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware')



Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/django/contrib/admin/options.py", line 696, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1898, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1758, in changeform_view
    with transaction.atomic(using=router.db_for_write(self.model)):
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/django/db/transaction.py", line 307, in __exit__
    connection.set_autocommit(True)
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/django/db/backends/base/base.py", line 487, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/django/db/backends/base/base.py", line 765, in run_and_clear_commit_hooks
    func()
  File "/Users/simon/Dropbox/Development/simonwillisonblog/blog/signals.py", line 39, in on_commit
    instance.__class__.objects.filter(pk=pk).update(
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/django/db/models/query.py", line 1206, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1982, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 230, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 154, in _record
    return method(sql, params)
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/simon/.local/share/virtualenvs/simonwillisonblog-izSE3ZQu/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)

Exception Type: IndexError at /admin/blog/entry/add/
Exception Value: tuple index out of range
```

**Comment by simonw** [comment]
Note that the entry did actually publish fine, so it was something that runs after the entry code (maybe relating to search indexing?)

**Comment by simonw** [comment]
Yeah, https://simonwillison.net/search/?q=chatgpt+internet is returning 0 results when it should be showing https://simonwillison.net/2023/Mar/10/chatgpt-internet-access/

I'm going to downgrade Django to 4 for the moment to see if that fixes it.

**Comment by simonw** [comment]
That fixed the bug - I edited the entry to trigger a search index and now https://simonwillison.net/search/?q=chatgpt++internet returns the expected result.
