### ISSUE TITLE
Cloud Run deploys of backup failing due to numpy

### ISSUE THREAD

**Issue by simonw** [simonw/simonwillisonblog#442]
https://github.com/simonw/simonwillisonblog-backup/actions/runs/9551338381/job/26325457935
```
Traceback (most recent call last):
  File "/usr/local/bin/datasette", line 5, in <module>
    from datasette.cli import cli
  File "/usr/local/lib/python3.11/site-packages/datasette/cli.py", line 15, in <module>
    from .app import (
  File "/usr/local/lib/python3.11/site-packages/datasette/app.py", line 31, in <module>
    from .views.database import DatabaseDownload, DatabaseView, TableCreateView
  File "/usr/local/lib/python3.11/site-packages/datasette/views/database.py", line 29, in <module>
    from datasette.plugins import pm
  File "/usr/local/lib/python3.11/site-packages/datasette/plugins.py", line 27, in <module>
    pm.load_setuptools_entrypoints("datasette")
  File "/usr/local/lib/python3.11/site-packages/pluggy/_manager.py", line 421, in load_setuptools_entrypoints
    plugin = ep.load()
             ^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 198, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/datasette_faiss/__init__.py", line 2, in <module>
    import faiss
  File "/usr/local/lib/python3.11/site-packages/faiss/__init__.py", line 16, in <module>
    from .loader import *
  File "/usr/local/lib/python3.11/site-packages/faiss/loader.py", line 98, in <module>
    from .swigfaiss import *
  File "/usr/local/lib/python3.11/site-packages/faiss/swigfaiss.py", line 10, in <module>
    from . import _swigfaiss
ImportError: numpy.core.multiarray failed to import
```
I think the numpy 2.0 release broke `datasette-faiss`.

**Comment by simonw** [comment]
- https://github.com/simonw/datasette-faiss/issues/4
