### ISSUE TITLE
CI test failure: test_draft_items_not_displayed

### ISSUE THREAD

**Issue by simonw** [simonw/simonwillisonblog#499]
https://github.com/simonw/simonwillisonblog/actions/runs/11414842854/job/31764245875
```
======================================================================
FAIL: test_draft_items_not_displayed (blog.tests.BlogTests.test_draft_items_not_displayed)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/simonwillisonblog/simonwillisonblog/blog/tests.py", line 201, in test_draft_items_not_displayed
    self.assertContains(response2, robots_fragment)
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/django/test/testcases.py", line 623, in assertContains
    self.assertTrue(
AssertionError: False is not true : Couldn't find '<meta name="robots" content="noindex">' in the following response
b'<!DOCTYPE html>\n<html lang="en-gb">\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n<link rel="canonical" href="https://simonwillison.net/2024/Sep/26/slug1/">\n<title>draftblogmark</title>\n<script defer data-domain="simonwillison.net" src="https://plausible.io/js/plausible.js"></script>\n\n<link rel="alternate" type="application/atom+xml" title="Atom" href="/atom/everything/">\n<link rel="stylesheet" type="text/css" href="/static/css/all.css">\n<link rel="webmention" href="https://webmention.io/simonwillison.net/webmention">\n<link rel="pingback" href="https://webmention.io/simonwillison.net/xmlrpc">\n\n\n\n<meta name="twitter:card" content="summary">\n\n<meta name="twitter:creator" content="@simonw">\n<meta property="og:url" content="https://simonwillison.net/2024/Sep/26/slug1/">\n<meta property="og:title" content="draftblogmark">\n\n<meta property="og:type" content="article">\n<meta property="og:descripti
```
But it passes on my laptop.

**Comment by simonw** [comment]
Well that's annoying, the test passed after I added `-v3`.
